package com.acme.scheduler.core.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import org.springframework.data.annotation.Id;

import java.time.LocalDateTime;

@Builder
@Getter
@AllArgsConstructor

@DynamoDBTable(tableName = "Schedule")
public class Schedule {

    @Id
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "UUID")
    private String UUID;

    @DynamoDBAttribute(attributeName = "fullname")
    private String fullname;
    @DynamoDBAttribute(attributeName = "phone")
    private String phone;
    @DynamoDBAttribute(attributeName = "serviceType")
    private String serviceType;
    @DynamoDBAttribute(attributeName = "date")
    private LocalDateTime date;

}
