package com.acme.scheduler.core.entities;

import com.acme.scheduler.core.enums.ServiceType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.time.LocalDateTime;

@Getter
@RequiredArgsConstructor
@DynamoDBTable(tableName = "Schedule")
public class Schedule {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "UUID")
    private String UUID;

    @DynamoDBAttribute(attributeName = "fullname")
    private String fullname;
    @DynamoDBAttribute(attributeName = "phone")
    private String phone;
    @DynamoDBAttribute(attributeName = "serviceType")
    private ServiceType serviceType;
    @DynamoDBAttribute(attributeName = "date")
    private LocalDateTime date;

}
