package com.acme.scheduler.core.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.data.annotation.Id;

import java.util.HashMap;
import java.util.List;

@DynamoDBTable(tableName = "Service")
public class Service {

    @Id
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "serviceId")
    private String serviceId;
    @DynamoDBAttribute(attributeName = "serviceName")
    private String serviceName;
    @DynamoDBAttribute(attributeName = "availableDate")
    private HashMap<String, List<String>> availableDate;

    public Service(String serviceName, HashMap<String, List<String>> availableDate) {
        this.serviceName = serviceName;
        this.availableDate = availableDate;
    }

    public String getServiceId() {
        return serviceId;
    }

    public String getServiceName() {
        return serviceName;
    }

    public HashMap<String, List<String>> getAvailableDate() {
        return availableDate;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public void setAvailableDate(HashMap<String, List<String>> availableDate) {
        this.availableDate = availableDate;
    }
}
