package com.acme.scheduler.core.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;
import java.util.Map;

@DynamoDBTable(tableName = "Service")
public class ServiceType {

    @DynamoDBHashKey(attributeName = "serviceId")
    @DynamoDBAutoGeneratedKey
    private String serviceId;
    @DynamoDBAttribute(attributeName = "serviceName")
    private String serviceName;
    @DynamoDBAttribute(attributeName = "availableDate")
    private Map<String, List<String>> availableDate;

    public ServiceType() {
    }

    public ServiceType(String serviceName, Map<String, List<String>> availableDate) {
        this.serviceName = serviceName;
        this.availableDate = availableDate;
    }

    public String getServiceId() {
        return serviceId;
    }

    public String getServiceName() {
        return serviceName;
    }

    public Map<String, List<String>> getAvailableDate() {
        return availableDate;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public void setAvailableDate(Map<String, List<String>> availableDate) {
        this.availableDate = availableDate;
    }
}
