package com.acme.scheduler.core.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import org.springframework.data.annotation.Id;

import java.util.HashMap;
import java.util.List;

@Builder
@Getter
@AllArgsConstructor

@DynamoDBTable(tableName = "Service")
public class Service {

    @Id
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "UUID")
    private String UUID;
    @DynamoDBAttribute(attributeName = "serviceName")
    private String serviceName;
    @DynamoDBAttribute(attributeName = "availableDate")
    private HashMap<String, List<String>> availableDate;

}
